import '../models/grx_federative_unit.model.dart';

abstract class GrxStaticValuesService {
  static const brStates = [
    GrxFederativeUnit(id: 'AC', name: 'Acre'),
    GrxFederativeUnit(id: 'AL', name: 'Alagoas'),
    GrxFederativeUnit(id: 'AP', name: 'Amapá'),
    GrxFederativeUnit(id: 'AM', name: 'Amazonas'),
    GrxFederativeUnit(id: 'BA', name: 'Bahía'),
    GrxFederativeUnit(id: 'CE', name: 'Ceará'),
    GrxFederativeUnit(id: 'DF', name: 'Distrito Federal'),
    GrxFederativeUnit(id: 'ES', name: 'Espírito Santo'),
    GrxFederativeUnit(id: 'GO', name: 'Goiás'),
    GrxFederativeUnit(id: 'MA', name: 'Maranhão'),
    GrxFederativeUnit(id: 'MT', name: 'Mato Grosso'),
    GrxFederativeUnit(id: 'MS', name: 'Mato Grosso do Sul'),
    GrxFederativeUnit(id: 'MG', name: 'Minas Geraís'),
    GrxFederativeUnit(id: 'PA', name: 'Pará'),
    GrxFederativeUnit(id: 'PB', name: 'Paraíba'),
    GrxFederativeUnit(id: 'PR', name: 'Paraná'),
    GrxFederativeUnit(id: 'PE', name: 'Pernambuco'),
    GrxFederativeUnit(id: 'PI', name: 'Piauí'),
    GrxFederativeUnit(id: 'RJ', name: 'Rio de Janeiro'),
    GrxFederativeUnit(id: 'RN', name: 'Rio Grande do Norte'),
    GrxFederativeUnit(id: 'RS', name: 'Rio Grande do Sul'),
    GrxFederativeUnit(id: 'RO', name: 'Rondônia'),
    GrxFederativeUnit(id: 'RR', name: 'Roraima'),
    GrxFederativeUnit(id: 'SC', name: 'Santa Catarina'),
    GrxFederativeUnit(id: 'SP', name: 'São Paulo'),
    GrxFederativeUnit(id: 'SE', name: 'Sergipe'),
    GrxFederativeUnit(id: 'TO', name: 'Tocantins'),
    GrxFederativeUnit(id: 'UKN', name: 'Não Informado'),
  ];

  static const usStates = [
    GrxFederativeUnit(id: 'AL', name: 'Alabama'),
    GrxFederativeUnit(id: 'AK', name: 'Alaska'),
    GrxFederativeUnit(id: 'AZ', name: 'Arizona'),
    GrxFederativeUnit(id: 'AR', name: 'Arkansas'),
    GrxFederativeUnit(id: 'CA', name: 'California'),
    GrxFederativeUnit(id: 'CZ', name: 'Canal Zone'),
    GrxFederativeUnit(id: 'CO', name: 'Colorado'),
    GrxFederativeUnit(id: 'CT', name: 'Connecticut'),
    GrxFederativeUnit(id: 'DE', name: 'Delaware'),
    GrxFederativeUnit(id: 'DC', name: 'District of Columbia'),
    GrxFederativeUnit(id: 'FL', name: 'Florida'),
    GrxFederativeUnit(id: 'GA', name: 'Georgia'),
    GrxFederativeUnit(id: 'GU', name: 'Guam'),
    GrxFederativeUnit(id: 'HI', name: 'Hawaii'),
    GrxFederativeUnit(id: 'ID', name: 'Idaho'),
    GrxFederativeUnit(id: 'IL', name: 'Illinois'),
    GrxFederativeUnit(id: 'IN', name: 'Indiana'),
    GrxFederativeUnit(id: 'IA', name: 'Iowa'),
    GrxFederativeUnit(id: 'KS', name: 'Kansas'),
    GrxFederativeUnit(id: 'KY', name: 'Kentucky'),
    GrxFederativeUnit(id: 'LA', name: 'Louisiana'),
    GrxFederativeUnit(id: 'ME', name: 'Maine'),
    GrxFederativeUnit(id: 'MD', name: 'Maryland'),
    GrxFederativeUnit(id: 'MA', name: 'Massachusetts'),
    GrxFederativeUnit(id: 'MI', name: 'Michigan'),
    GrxFederativeUnit(id: 'MN', name: 'Minnesota'),
    GrxFederativeUnit(id: 'MS', name: 'Mississippi'),
    GrxFederativeUnit(id: 'MO', name: 'Missouri'),
    GrxFederativeUnit(id: 'MT', name: 'Montana'),
    GrxFederativeUnit(id: 'NE', name: 'Nebraska'),
    GrxFederativeUnit(id: 'NV', name: 'Nevada'),
    GrxFederativeUnit(id: 'NH', name: 'New Hampshire'),
    GrxFederativeUnit(id: 'NJ', name: 'New Jersey'),
    GrxFederativeUnit(id: 'NM', name: 'New Mexico'),
    GrxFederativeUnit(id: 'NY', name: 'New York'),
    GrxFederativeUnit(id: 'NC', name: 'North Carolina'),
    GrxFederativeUnit(id: 'ND', name: 'North Dakota'),
    GrxFederativeUnit(id: 'OH', name: 'Ohio'),
    GrxFederativeUnit(id: 'OK', name: 'Oklahoma'),
    GrxFederativeUnit(id: 'OR', name: 'Oregon'),
    GrxFederativeUnit(id: 'PA', name: 'Pennsylvania'),
    GrxFederativeUnit(id: 'PR', name: 'Puerto Rico'),
    GrxFederativeUnit(id: 'RI', name: 'Rhode Island'),
    GrxFederativeUnit(id: 'SC', name: 'South Carolina'),
    GrxFederativeUnit(id: 'SD', name: 'South Dakota'),
    GrxFederativeUnit(id: 'TN', name: 'Tennessee'),
    GrxFederativeUnit(id: 'TX', name: 'Texas'),
    GrxFederativeUnit(id: 'UT', name: 'Utah'),
    GrxFederativeUnit(id: 'VT', name: 'Vermont'),
    GrxFederativeUnit(id: 'VI', name: 'Virgin Islands'),
    GrxFederativeUnit(id: 'VA', name: 'Virginia'),
    GrxFederativeUnit(id: 'WA', name: 'Washington'),
    GrxFederativeUnit(id: 'WV', name: 'West Virginia'),
    GrxFederativeUnit(id: 'WI', name: 'Wisconsin'),
    GrxFederativeUnit(id: 'WY', name: 'Wyoming'),
    GrxFederativeUnit(id: 'UKN', name: 'Não Informado'),
  ];

  static const arStates = [
    GrxFederativeUnit(id: 'DF', name: 'Autonomous City of Buenos Aires'),
    GrxFederativeUnit(id: 'BA', name: 'Buenos Aires'),
    GrxFederativeUnit(id: 'CT', name: 'Catamarca'),
    GrxFederativeUnit(id: 'CC', name: 'Chaco'),
    GrxFederativeUnit(id: 'CH', name: 'Chubut'),
    GrxFederativeUnit(id: 'CB', name: 'Córdoba'),
    GrxFederativeUnit(id: 'CN', name: 'Corrientes'),
    GrxFederativeUnit(id: 'ER', name: 'Entre Ríos'),
    GrxFederativeUnit(id: 'FM', name: 'Formosa'),
    GrxFederativeUnit(id: 'JY', name: 'Jujuy'),
    GrxFederativeUnit(id: 'LP', name: 'La Pampa'),
    GrxFederativeUnit(id: 'LR', name: 'La Rioja'),
    GrxFederativeUnit(id: 'MZ', name: 'Mendoza'),
    GrxFederativeUnit(id: 'MN', name: 'Misiones'),
    GrxFederativeUnit(id: 'NQ', name: 'Neuquén'),
    GrxFederativeUnit(id: 'RN', name: 'Río Negro'),
    GrxFederativeUnit(id: 'SA', name: 'Salta'),
    GrxFederativeUnit(id: 'SJ', name: 'San Juan'),
    GrxFederativeUnit(id: 'SL', name: 'San Luis'),
    GrxFederativeUnit(id: 'SC', name: 'Santa Cruz'),
    GrxFederativeUnit(id: 'SF', name: 'Santa Fe'),
    GrxFederativeUnit(id: 'SE', name: 'Santiago del Estero'),
    GrxFederativeUnit(
        id: 'TF',
        name: 'Tierra del Fuego, Antártida e Islas del Atlántico Sur'),
    GrxFederativeUnit(id: 'TM', name: 'Tucumán'),
  ];

  static const uyStates = [
    GrxFederativeUnit(id: 'AR', name: 'Artigas'),
    GrxFederativeUnit(id: 'CA', name: 'Canelones'),
    GrxFederativeUnit(id: 'CL', name: 'Cerro Largo'),
    GrxFederativeUnit(id: 'CO', name: 'Colonia'),
    GrxFederativeUnit(id: 'DU', name: 'Durazno'),
    GrxFederativeUnit(id: 'FS', name: 'Flores'),
    GrxFederativeUnit(id: 'FD', name: 'Florida'),
    GrxFederativeUnit(id: 'LA', name: 'Lavalleja'),
    GrxFederativeUnit(id: 'MA', name: 'Maldonado'),
    GrxFederativeUnit(id: 'MO', name: 'Montevideo'),
    GrxFederativeUnit(id: 'PA', name: 'Paysandú'),
    GrxFederativeUnit(id: 'RN', name: 'Río Negro'),
    GrxFederativeUnit(id: 'RV', name: 'Rivera'),
    GrxFederativeUnit(id: 'RO', name: 'Rocha'),
    GrxFederativeUnit(id: 'SA', name: 'Salto'),
    GrxFederativeUnit(id: 'SJ', name: 'San José'),
    GrxFederativeUnit(id: 'SO', name: 'Soriano'),
    GrxFederativeUnit(id: 'TA', name: 'Tacuarembó'),
    GrxFederativeUnit(id: 'TT', name: 'Treinta y Tres'),
  ];

  static const mzStates = [
    GrxFederativeUnit(id: '1', name: '1 - Niassa'),
    GrxFederativeUnit(id: '2', name: '2 - Cabo Delgado'),
    GrxFederativeUnit(id: '3', name: '3 - Nampula'),
    GrxFederativeUnit(id: '4', name: '4 - Zambézia'),
    GrxFederativeUnit(id: '5', name: '5 - Tete'),
    GrxFederativeUnit(id: '6', name: '6 - Manica'),
    GrxFederativeUnit(id: '7', name: '7 - Sofala'),
    GrxFederativeUnit(id: '8', name: '8 - Inhambane'),
    GrxFederativeUnit(id: '9', name: '9 - Gaza'),
    GrxFederativeUnit(id: '10', name: '10 - Maputo'),
    GrxFederativeUnit(id: '11', name: '11 - Maputo'),
  ];
}
