import '../enums/grx_country_id.enum.dart';
import '../models/grx_country.model.dart';
import '../services/grx_static_values.service.dart';

abstract class GrxCountryUtils {
  static GrxCountry? getCountry(final GrxCountryId? id) => countries
      .map<GrxCountry?>((x) => x)
      .firstWhere((country) => country!.id == id, orElse: () => null);

  static const countries = <GrxCountry>[
    GrxCountry(
      id: GrxCountryId.BR,
      code: '+55',
      name: 'Brasil',
      flag: 'brazil_flag',
      language: 'pt-BR',
      phoneMasks: [
        '(##) ####-#####',
        '(##) #####-####',
      ],
      zipcodeMasks: [
        '#####-###',
      ],
      states: GrxStaticValuesService.brStates,
    ),
    GrxCountry(
      id: GrxCountryId.US,
      code: '+1',
      name: 'Estados Unidos',
      flag: 'united_states_flag',
      language: 'en-US',
      phoneMasks: [
        '(###) ###-####',
      ],
      states: GrxStaticValuesService.usStates,
    ),
    GrxCountry(
      id: GrxCountryId.AR,
      code: '+54',
      name: 'Argentina',
      flag: 'argentina_flag',
      language: 'es',
      phoneMasks: [
        '### ####-####',
      ],
      states: GrxStaticValuesService.arStates,
    ),
    GrxCountry(
      id: GrxCountryId.UY,
      code: '+598',
      name: 'Uruguai',
      flag: 'uruguay_flag',
      language: 'es',
      phoneMasks: [
        '### ####-####',
      ],
      states: GrxStaticValuesService.uyStates,
    ),
    GrxCountry(
      id: GrxCountryId.AF,
      code: '+93',
      name: 'Afeganistão',
      flag: 'afghanistan_flag',
    ),
    GrxCountry(
      id: GrxCountryId.ZA,
      code: '+27',
      name: 'África do Sul',
      flag: 'south_africa_flag',
    ),
    GrxCountry(
      id: GrxCountryId.AL,
      code: '+355',
      name: 'Albânia',
      flag: 'albania_flag',
    ),
    GrxCountry(
      id: GrxCountryId.DE,
      code: '+49',
      name: 'Alemanha',
      flag: 'germany_flag',
    ),
    GrxCountry(
      id: GrxCountryId.AD,
      code: '+376',
      name: 'Andorra',
      flag: 'andorra_flag',
    ),
    GrxCountry(
      id: GrxCountryId.AO,
      code: '+244',
      name: 'Angola',
      flag: 'angola_flag',
    ),
    GrxCountry(
      id: GrxCountryId.AI,
      code: '+1',
      name: 'Anguilla',
      flag: 'anguilla_flag',
    ),
    GrxCountry(
      id: GrxCountryId.AG,
      code: '+1',
      name: 'Antígua e Barbuda',
      flag: 'antigua_and_barbuda_flag',
    ),
    GrxCountry(
      id: GrxCountryId.SA,
      code: '+966',
      name: 'Arábia Saudita',
      flag: 'saudi_arabia_flag',
    ),
    GrxCountry(
      id: GrxCountryId.DZ,
      code: '+213',
      name: 'Argélia',
      flag: 'algeria_flag',
    ),
    GrxCountry(
      id: GrxCountryId.AM,
      code: '+374',
      name: 'Armênia',
      flag: 'armenia_flag',
    ),
    GrxCountry(
      id: GrxCountryId.AW,
      code: '+297',
      name: 'Aruba',
      flag: 'aruba_flag',
    ),
    GrxCountry(
      id: GrxCountryId.AU,
      code: '+61',
      name: 'Austrália',
      flag: 'australia_flag',
    ),
    GrxCountry(
      id: GrxCountryId.AT,
      code: '+43',
      name: 'Áustria',
      flag: 'austria_flag',
    ),
    GrxCountry(
      id: GrxCountryId.AZ,
      code: '+994',
      name: 'Azerbaijão',
      flag: 'azerbaijan_flag',
    ),
    GrxCountry(
      id: GrxCountryId.BS,
      code: '+1',
      name: 'Bahamas',
      flag: 'bahamas_flag',
    ),
    GrxCountry(
      id: GrxCountryId.BD,
      code: '+880',
      name: 'Bangladesh',
      flag: 'bangladesh_flag',
    ),
    GrxCountry(
      id: GrxCountryId.BB,
      code: '+1',
      name: 'Barbados',
      flag: 'barbados_flag',
    ),
    GrxCountry(
      id: GrxCountryId.BH,
      code: '+973',
      name: 'Bahrein',
      flag: 'bahrain_flag',
    ),
    GrxCountry(
      id: GrxCountryId.BE,
      code: '+32',
      name: 'Bélgica',
      flag: 'belgium_flag',
    ),
    GrxCountry(
      id: GrxCountryId.BZ,
      code: '+501',
      name: 'Belize',
      flag: 'belize_flag',
    ),
    GrxCountry(
      id: GrxCountryId.BJ,
      code: '+229',
      name: 'Benim',
      flag: 'benin_flag',
    ),
    GrxCountry(
      id: GrxCountryId.BM,
      code: '+1',
      name: 'Bermudas',
      flag: 'bermuda_flag',
    ),
    GrxCountry(
      id: GrxCountryId.BY,
      code: '+375',
      name: 'Bielorrússia',
      flag: 'belarus_flag',
    ),
    GrxCountry(
      id: GrxCountryId.BO,
      code: '+591',
      name: 'Bolívia',
      flag: 'bolivia_flag',
    ),
    GrxCountry(
      id: GrxCountryId.BA,
      code: '+387',
      name: 'Bósnia e Herzegovina',
      flag: 'bosnia_and_herzegovina_flag',
    ),
    GrxCountry(
      id: GrxCountryId.BW,
      code: '+267',
      name: 'Botswana',
      flag: 'botswana_flag',
    ),
    GrxCountry(
      id: GrxCountryId.BN,
      code: '+673',
      name: 'Brunei',
      flag: 'brunei_flag',
    ),
    GrxCountry(
      id: GrxCountryId.BG,
      code: '+359',
      name: 'Bulgária',
      flag: 'bulgaria_flag',
    ),
    GrxCountry(
      id: GrxCountryId.BI,
      code: '+257',
      name: 'Burundi',
      flag: 'burundi_flag',
    ),
    GrxCountry(
      id: GrxCountryId.BT,
      code: '+975',
      name: 'Butão',
      flag: 'bhutan_flag',
    ),
    GrxCountry(
      id: GrxCountryId.KH,
      code: '+855',
      name: 'Camboja',
      flag: 'cambodia_flag',
    ),
    GrxCountry(
      id: GrxCountryId.CA,
      code: '+1',
      name: 'Canadá',
      flag: 'canada_flag',
    ),
    GrxCountry(
      id: GrxCountryId.KZ,
      code: '+7',
      name: 'Cazaquistão',
      flag: 'kazakhstan_flag',
    ),
    GrxCountry(
      id: GrxCountryId.TD,
      code: '+235',
      name: 'Chade',
      flag: 'chad_flag',
    ),
    GrxCountry(
      id: GrxCountryId.CL,
      code: '+56',
      name: 'Chile',
      flag: 'chile_flag',
    ),
    GrxCountry(
      id: GrxCountryId.CN,
      code: '+86',
      name: 'China',
      flag: 'china_flag',
    ),
    GrxCountry(
      id: GrxCountryId.CY,
      code: '+357',
      name: 'Chipre',
      flag: 'northern_cyprus_flag',
    ),
    GrxCountry(
      id: GrxCountryId.CO,
      code: '+57',
      name: 'Colômbia',
      flag: 'colombia_flag',
    ),
    GrxCountry(
      id: GrxCountryId.KM,
      code: '+269',
      name: 'Comores',
      flag: 'comoros_flag',
    ),
    GrxCountry(
      id: GrxCountryId.KP,
      code: '+850',
      name: 'Coreia do Norte',
      flag: 'north_korea_flag',
    ),
    GrxCountry(
      id: GrxCountryId.KR,
      code: '+82',
      name: 'Coreia do Sul',
      flag: 'south_korea_flag',
    ),
    GrxCountry(
      id: GrxCountryId.CI,
      code: '+225',
      name: 'Costa do Marfim',
      flag: 'ivory_coast_flag',
    ),
    GrxCountry(
      id: GrxCountryId.CR,
      code: '+506',
      name: 'Costa Rica',
      flag: 'costa_rica_flag',
    ),
    GrxCountry(
      id: GrxCountryId.HR,
      code: '+385',
      name: 'Croácia',
      flag: 'croatia_flag',
    ),
    GrxCountry(
      id: GrxCountryId.CU,
      code: '+53',
      name: 'Cuba',
      flag: 'cuba_flag',
    ),
    GrxCountry(
      id: GrxCountryId.DK,
      code: '+45',
      name: 'Dinamarca',
      flag: 'denmark_flag',
    ),
    GrxCountry(
      id: GrxCountryId.DJ,
      code: '+253',
      name: 'Dijibuti',
      flag: 'djibouti_flag',
    ),
    GrxCountry(
      id: GrxCountryId.DM,
      code: '+1',
      name: 'Dominica',
      flag: 'dominica_flag',
    ),
    GrxCountry(
      id: GrxCountryId.EG,
      code: '+20',
      name: 'Egito',
      flag: 'egypt_flag',
    ),
    GrxCountry(
      id: GrxCountryId.SV,
      code: '+503',
      name: 'El Salvador',
      flag: 'el_salvador_flag',
    ),
    GrxCountry(
      id: GrxCountryId.AE,
      code: '+971',
      name: 'Emirados Árabes Unidos',
      flag: 'united_arab_emirates_flag',
    ),
    GrxCountry(
      id: GrxCountryId.EC,
      code: '+593',
      name: 'Equador',
      flag: 'ecuador_flag',
    ),
    GrxCountry(
      id: GrxCountryId.ER,
      code: '+291',
      name: 'Eritreia',
      flag: 'eritrea_flag',
    ),
    GrxCountry(
      id: GrxCountryId.SK,
      code: '+421',
      name: 'Eslováquia',
      flag: 'slovakia_flag',
    ),
    GrxCountry(
      id: GrxCountryId.SI,
      code: '+386',
      name: 'Eslovênia',
      flag: 'slovenia_flag',
    ),
    GrxCountry(
      id: GrxCountryId.ES,
      code: '+34',
      name: 'Espanha',
      flag: 'spain_flag',
    ),
    GrxCountry(
      id: GrxCountryId.EE,
      code: '+372',
      name: 'Estônia',
      flag: 'estonia_flag',
    ),
    GrxCountry(
      id: GrxCountryId.ET,
      code: '+251',
      name: 'Etiópia',
      flag: 'ethiopia_flag',
    ),
    GrxCountry(
      id: GrxCountryId.FJ,
      code: '+679',
      name: 'Fiji',
      flag: 'fiji_flag',
    ),
    GrxCountry(
      id: GrxCountryId.PH,
      code: '+63',
      name: 'Filipinas',
      flag: 'philippines_flag',
    ),
    GrxCountry(
      id: GrxCountryId.FI,
      code: '+358',
      name: 'Finlândia',
      flag: 'finland_flag',
    ),
    GrxCountry(
      id: GrxCountryId.FR,
      code: '+33',
      name: 'França',
      flag: 'france_flag',
    ),
    GrxCountry(
      id: GrxCountryId.GA,
      code: '+241',
      name: 'Gabão',
      flag: 'gabon_flag',
    ),
    GrxCountry(
      id: GrxCountryId.GM,
      code: '+220',
      name: 'Gâmbia',
      flag: 'gambia_flag',
    ),
    GrxCountry(
      id: GrxCountryId.GH,
      code: '+233',
      name: 'Ghana',
      flag: 'ghana_flag',
    ),
    GrxCountry(
      id: GrxCountryId.GE,
      code: '+995',
      name: 'Geórgia',
      flag: 'georgia_flag',
    ),
    GrxCountry(
      id: GrxCountryId.GI,
      code: '+350',
      name: 'Gibraltar',
      flag: 'gibraltar_flag',
    ),
    GrxCountry(
      id: GrxCountryId.GD,
      code: '+1',
      name: 'Granada',
      flag: 'grenada_flag',
    ),
    GrxCountry(
      id: GrxCountryId.GR,
      code: '+30',
      name: 'Grécia',
      flag: 'greece_flag',
    ),
    GrxCountry(
      id: GrxCountryId.GL,
      code: '+299',
      name: 'Groenlândia',
      flag: 'greenland_flag',
    ),
    GrxCountry(
      id: GrxCountryId.GU,
      code: '+671',
      name: 'Guam',
      flag: 'guam_flag',
    ),
    GrxCountry(
      id: GrxCountryId.GT,
      code: '+502',
      name: 'Guatemala',
      flag: 'guatemala_flag',
    ),
    GrxCountry(
      id: GrxCountryId.GN,
      code: '+224',
      name: 'Guiné',
      flag: 'guinea_flag',
    ),
    GrxCountry(
      id: GrxCountryId.GW,
      code: '+245',
      name: 'Guiné-Bissau',
      flag: 'guinea_bissau_flag',
    ),
    GrxCountry(
      id: GrxCountryId.HT,
      code: '+509',
      name: 'Haiti',
      flag: 'haiti_flag',
    ),
    GrxCountry(
      id: GrxCountryId.NL,
      code: '+31',
      name: 'Holanda',
      flag: 'netherlands_flag',
    ),
    GrxCountry(
      id: GrxCountryId.HN,
      code: '+504',
      name: 'Honduras',
      flag: 'honduras_flag',
    ),
    GrxCountry(
      id: GrxCountryId.HK,
      code: '+852',
      name: 'Hong Kong',
      flag: 'hong_kong_flag',
    ),
    GrxCountry(
      id: GrxCountryId.HU,
      code: '+36',
      name: 'Hungria',
      flag: 'hungary_flag',
    ),
    GrxCountry(
      id: GrxCountryId.YE,
      code: '+967',
      name: 'Iêmen',
      flag: 'yemen_flag',
    ),
    GrxCountry(
      id: GrxCountryId.KY,
      code: '+1',
      name: 'Ilhas Cayman',
      flag: 'cayman_islands_flag',
    ),
    GrxCountry(
      id: GrxCountryId.CX,
      code: '+672',
      name: 'Ilha Christmas',
      flag: 'christmas_island_flag',
    ),
    GrxCountry(
      id: GrxCountryId.CC,
      code: '+672',
      name: 'Ilhas Cocos',
      flag: 'cocos_island_flag',
    ),
    GrxCountry(
      id: GrxCountryId.CK,
      code: '+682',
      name: 'Ilhas Cook',
      flag: 'cook_islands_flag',
    ),
    GrxCountry(
      id: GrxCountryId.MV,
      code: '+960',
      name: 'Maldivas',
      flag: 'maldives_flag',
    ),
    GrxCountry(
      id: GrxCountryId.MP,
      code: '+1',
      name: 'Ilhas Marianas do Norte',
      flag: 'northern_marianas_islands_flag',
    ),
    GrxCountry(
      id: GrxCountryId.MH,
      code: '+692',
      name: 'Ilhas Marshall',
      flag: 'marshall_island_flag',
    ),
    GrxCountry(
      id: GrxCountryId.NF,
      code: '+672',
      name: 'Ilha Norfolk',
      flag: 'norfolk_island_flag',
    ),
    GrxCountry(
      id: GrxCountryId.SB,
      code: '+677',
      name: 'Ilhas Salomão',
      flag: 'solomon_islands_flag',
    ),
    GrxCountry(
      id: GrxCountryId.VI,
      code: '+1',
      name: 'Ilhas Virgens Americanas',
      flag: 'virgin_islands_flag',
    ),
    GrxCountry(
      id: GrxCountryId.VG,
      code: '+1',
      name: 'Ilhas Virgens Britânicas',
      flag: 'british_virgin_islands_flag',
    ),
    GrxCountry(
      id: GrxCountryId.IN,
      code: '+91',
      name: 'Índia',
      flag: 'india_flag',
    ),
    GrxCountry(
      id: GrxCountryId.ID,
      code: '+62',
      name: 'Indonésia',
      flag: 'indonesia_flag',
    ),
    GrxCountry(
      id: GrxCountryId.IR,
      code: '+98',
      name: 'Irã',
      flag: 'iran_flag',
    ),
    GrxCountry(
      id: GrxCountryId.IQ,
      code: '+964',
      name: 'Iraque',
      flag: 'iraq_flag',
    ),
    GrxCountry(
      id: GrxCountryId.IE,
      code: '+353',
      name: 'Irlanda',
      flag: 'ireland_flag',
    ),
    GrxCountry(
      id: GrxCountryId.ISL,
      code: '+354',
      name: 'Islândia',
      flag: 'iceland_flag',
    ),
    GrxCountry(
      id: GrxCountryId.IL,
      code: '+972',
      name: 'Israel',
      flag: 'israel_flag',
    ),
    GrxCountry(
      id: GrxCountryId.IT,
      code: '+39',
      name: 'Itália',
      flag: 'italy_flag',
    ),
    GrxCountry(
      id: GrxCountryId.JM,
      code: '+1',
      name: 'Jamaica',
      flag: 'jamaica_flag',
    ),
    GrxCountry(
      id: GrxCountryId.JP,
      code: '+81',
      name: 'Japão',
      flag: 'japan_flag',
    ),
    GrxCountry(
      id: GrxCountryId.JO,
      code: '+962',
      name: 'Jordânia',
      flag: 'jordan_flag',
    ),
    GrxCountry(
      id: GrxCountryId.KI,
      code: '+686',
      name: 'Kiribati',
      flag: 'kiribati_flag',
    ),
    // GrxCountry(
    //   code: '+383',
    //   name: 'Kosovo',
    //   flag: 'kosovo_flag',
    // ),
    GrxCountry(
      id: GrxCountryId.KW,
      code: '+965',
      name: 'Kuwait',
      flag: 'kwait_flag',
    ),
    GrxCountry(
      id: GrxCountryId.LA,
      code: '+856',
      name: 'Laos',
      flag: 'laos_flag',
    ),
    GrxCountry(
      id: GrxCountryId.LS,
      code: '+266',
      name: 'Lesoto',
      flag: 'lesotho_flag',
    ),
    GrxCountry(
      id: GrxCountryId.LV,
      code: '+371',
      name: 'Letônia',
      flag: 'latvia_flag',
    ),
    GrxCountry(
      id: GrxCountryId.LB,
      code: '+961',
      name: 'Líbano',
      flag: 'lebanon_flag',
    ),
    GrxCountry(
      id: GrxCountryId.LR,
      code: '+231',
      name: 'Libéria',
      flag: 'liberia_flag',
    ),
    GrxCountry(
      id: GrxCountryId.LY,
      code: '+218',
      name: 'Líbia',
      flag: 'libya_flag',
    ),
    GrxCountry(
      id: GrxCountryId.LI,
      code: '+237',
      name: 'Liechtenstein',
      flag: 'liechtenstein_flag',
    ),
    GrxCountry(
      id: GrxCountryId.LT,
      code: '+370',
      name: 'Lituânia',
      flag: 'lithuania_flag',
    ),
    GrxCountry(
      id: GrxCountryId.LU,
      code: '+352',
      name: 'Luxemburgo',
      flag: 'luxembourg_flag',
    ),
    GrxCountry(
      id: GrxCountryId.MO,
      code: '+853',
      name: 'Macau',
      flag: 'macao_flag',
    ),
    GrxCountry(
      id: GrxCountryId.MK,
      code: '+389',
      name: 'Macedônia',
      flag: 'republic_of_macedonia_flag',
    ),
    GrxCountry(
      id: GrxCountryId.MG,
      code: '+261',
      name: 'Madagascar',
      flag: 'madagascar_flag',
    ),
    GrxCountry(
      id: GrxCountryId.MY,
      code: '+60',
      name: 'Malásia',
      flag: 'malasya_flag',
    ),
    GrxCountry(
      id: GrxCountryId.MY,
      code: '+265',
      name: 'Malawi',
      flag: 'malawi_flag',
    ),
    GrxCountry(
      id: GrxCountryId.ML,
      code: '+223',
      name: 'Mali',
      flag: 'mali_flag',
    ),
    GrxCountry(
      id: GrxCountryId.MT,
      code: '+356',
      name: 'Malta',
      flag: 'malta_flag',
    ),
    GrxCountry(
      id: GrxCountryId.MA,
      code: '+212',
      name: 'Marrocos',
      flag: 'morocco_flag',
    ),
    GrxCountry(
      id: GrxCountryId.MQ,
      code: '+596',
      name: 'Martinica',
      flag: 'martinique_flag',
    ),
    GrxCountry(
      id: GrxCountryId.MU,
      code: '+230',
      name: 'Maurícia',
      flag: 'mauritius_flag',
    ),
    GrxCountry(
      id: GrxCountryId.MR,
      code: '+222',
      name: 'Mauritânia',
      flag: 'mauritania_flag',
    ),
    GrxCountry(
      id: GrxCountryId.MX,
      code: '+52',
      name: 'México',
      flag: 'mexico_flag',
    ),
    GrxCountry(
      id: GrxCountryId.FM,
      code: '+237',
      name: 'Micronesia',
      flag: 'micronesia_flag',
    ),
    GrxCountry(
      id: GrxCountryId.MZ,
      code: '+258',
      name: 'Moçambique',
      flag: 'mozambique_flag',
      phoneMasks: [
        '## ### ####',
      ],
      states: GrxStaticValuesService.mzStates,
    ),
    GrxCountry(
      id: GrxCountryId.MD,
      code: '+373',
      name: 'Moldávia',
      flag: 'moldova_flag',
    ),
    GrxCountry(
      id: GrxCountryId.MC,
      code: '+377',
      name: 'Mônaco',
      flag: 'monaco_flag',
    ),
    GrxCountry(
      id: GrxCountryId.MN,
      code: '+976',
      name: 'Mongólia',
      flag: 'mongolia_flag',
    ),
    GrxCountry(
      id: GrxCountryId.ME,
      code: '+382',
      name: 'Montenegro',
      flag: 'montenegro_flag',
    ),
    GrxCountry(
      id: GrxCountryId.MS,
      code: '+1',
      name: 'Montserrat',
      flag: 'montserrat_flag',
    ),
    GrxCountry(
      id: GrxCountryId.MM,
      code: '+95',
      name: 'Myanmar',
      flag: 'myanmar_flag',
    ),
    GrxCountry(
      id: GrxCountryId.NA,
      code: '+264',
      name: 'Namíbia',
      flag: 'namibia_flag',
    ),
    GrxCountry(
      id: GrxCountryId.NR,
      code: '+674',
      name: 'Nauru',
      flag: 'nauru_flag',
    ),
    GrxCountry(
      id: GrxCountryId.NP,
      code: '+977',
      name: 'Nepal',
      flag: 'nepal_flag',
    ),
    GrxCountry(
      id: GrxCountryId.NI,
      code: '+505',
      name: 'Nicarágua',
      flag: 'nicaragua_flag',
    ),
    GrxCountry(
      id: GrxCountryId.NE,
      code: '+227',
      name: 'Níger',
      flag: 'niger_flag',
    ),
    GrxCountry(
      id: GrxCountryId.NG,
      code: '+234',
      name: 'Nigéria',
      flag: 'nigeria_flag',
    ),
    GrxCountry(
      id: GrxCountryId.NU,
      code: '+683',
      name: 'Niue',
      flag: 'niue_flag',
    ),
    GrxCountry(
      id: GrxCountryId.NO,
      code: '+47',
      name: 'Noruega',
      flag: 'norway_flag',
    ),
    GrxCountry(
      id: GrxCountryId.NZ,
      code: '+64',
      name: 'Nova Zelândia',
      flag: 'new_zealand_flag',
    ),
    GrxCountry(
      id: GrxCountryId.OM,
      code: '+968',
      name: 'Omã',
      flag: 'oman_flag',
    ),
    GrxCountry(
      id: GrxCountryId.PW,
      code: '+680',
      name: 'Palau',
      flag: 'palau_flag',
    ),
    GrxCountry(
      id: GrxCountryId.PS,
      code: '+970',
      name: 'Palestina',
      flag: 'palestine_flag',
    ),
    GrxCountry(
      id: GrxCountryId.PA,
      code: '+507',
      name: 'Panamá',
      flag: 'panama_flag',
    ),
    GrxCountry(
      id: GrxCountryId.PG,
      code: '+675',
      name: 'Papua-Nova Guiné',
      flag: 'papua_new_guinea_flag',
    ),
    GrxCountry(
      id: GrxCountryId.PK,
      code: '+92',
      name: 'Paquistão',
      flag: 'pakistan_flag',
    ),
    GrxCountry(
      id: GrxCountryId.PY,
      code: '+595',
      name: 'Paraguai',
      flag: 'paraguay_flag',
    ),
    GrxCountry(
      id: GrxCountryId.PE,
      code: '+51',
      name: 'Peru',
      flag: 'peru_flag',
    ),
    GrxCountry(
      id: GrxCountryId.PF,
      code: '+689',
      name: 'Polinésia Francesa',
      flag: 'french_polynesia_flag',
    ),
    GrxCountry(
      id: GrxCountryId.PL,
      code: '+48',
      name: 'Polônia',
      flag: 'poland_flag',
    ),
    GrxCountry(
      id: GrxCountryId.PR,
      code: '+1',
      name: 'Porto Rico',
      flag: 'puerto_rico_flag',
    ),
    GrxCountry(
      id: GrxCountryId.PT,
      code: '+351',
      name: 'Portugal',
      flag: 'portugal_flag',
    ),
    GrxCountry(
      id: GrxCountryId.QA,
      code: '+974',
      name: 'Qatar',
      flag: 'qatar_flag',
    ),
    GrxCountry(
      id: GrxCountryId.KE,
      code: '+254',
      name: 'Quênia',
      flag: 'kenya_flag',
    ),
    GrxCountry(
      id: GrxCountryId.KG,
      code: '+996',
      name: 'Quirguistão',
      flag: 'kyrgyzstan_flag',
    ),
    GrxCountry(
      id: GrxCountryId.GB,
      code: '+44',
      name: 'Reino Unido',
      flag: 'united_kingdom_flag',
    ),
    GrxCountry(
      id: GrxCountryId.CF,
      code: '+236',
      name: 'República Centro-Africana',
      flag: 'central_african_republic_flag',
    ),
    GrxCountry(
      id: GrxCountryId.DO,
      code: '+1',
      name: 'República Dominicana',
      flag: 'dominican_republic_flag',
    ),
    GrxCountry(
      id: GrxCountryId.CZ,
      code: '+420',
      name: 'República Tcheca',
      flag: 'czech_republic_flag',
    ),
    GrxCountry(
      id: GrxCountryId.RO,
      code: '+40',
      name: 'Romênia',
      flag: 'romania_flag',
    ),
    GrxCountry(
      id: GrxCountryId.RW,
      code: '+250',
      name: 'Ruanda',
      flag: 'rwanda_flag',
    ),
    GrxCountry(
      id: GrxCountryId.RU,
      code: '+7',
      name: 'Rússia',
      flag: 'russia_flag',
    ),
    GrxCountry(
      id: GrxCountryId.WS,
      code: '+685',
      name: 'Samoa',
      flag: 'samoa_flag',
    ),
    GrxCountry(
      id: GrxCountryId.AS,
      code: '+1',
      name: 'Samoa Americana',
      flag: 'american_samoa_flag',
    ),
    GrxCountry(
      id: GrxCountryId.LC,
      code: '+1',
      name: 'Santa Lúcia',
      flag: 'st_lucia_flag',
    ),
    GrxCountry(
      id: GrxCountryId.KN,
      code: '+1',
      name: 'São Cristóvão e Nevis',
      flag: 'saint_kitts_and_nevis_flag',
    ),
    GrxCountry(
      id: GrxCountryId.SM,
      code: '+378',
      name: 'São Marinho',
      flag: 'san_marino_flag',
    ),
    GrxCountry(
      id: GrxCountryId.ST,
      code: '+239',
      name: 'São Tomé e Príncipe',
      flag: 'sao_tome_and_prince_flag',
    ),
    GrxCountry(
      id: GrxCountryId.VC,
      code: '+1',
      name: 'São Vicente e Granadinas',
      flag: 'st_vincent_and_the_grenadines_flag',
    ),
    GrxCountry(
      id: GrxCountryId.SC,
      code: '+248',
      name: 'Seicheles',
      flag: 'seychelles_flag',
    ),
    GrxCountry(
      id: GrxCountryId.SN,
      code: '+221',
      name: 'Senegal',
      flag: 'senegal_flag',
    ),
    GrxCountry(
      id: GrxCountryId.SL,
      code: '+232',
      name: 'Serra Leoa',
      flag: 'sierra_leone_flag',
    ),
    GrxCountry(
      id: GrxCountryId.RS,
      code: '+381',
      name: 'Sérvia',
      flag: 'serbia_flag',
    ),
    GrxCountry(
      id: GrxCountryId.SG,
      code: '+65',
      name: 'Singapura',
      flag: 'singapore_flag',
    ),
    GrxCountry(
      id: GrxCountryId.SY,
      code: '+963',
      name: 'Síria',
      flag: 'syria_flag',
    ),
    GrxCountry(
      id: GrxCountryId.SO,
      code: '+252',
      name: 'Somália',
      flag: 'somalia_flag',
    ),
    GrxCountry(
      id: GrxCountryId.LK,
      code: '+94',
      name: 'Sri Lanka',
      flag: 'sri_lanka_flag',
    ),
    GrxCountry(
      id: GrxCountryId.SD,
      code: '+249',
      name: 'Sudão',
      flag: 'sudan_flag',
    ),
    GrxCountry(
      id: GrxCountryId.SS,
      code: '+211',
      name: 'Sudão do Sul',
      flag: 'south_sudan_flag',
    ),
    GrxCountry(
      id: GrxCountryId.SE,
      code: '+46',
      name: 'Suécia',
      flag: 'sweden_flag',
    ),
    GrxCountry(
      id: GrxCountryId.CH,
      code: '+41',
      name: 'Suíça',
      flag: 'switzerland_flag',
    ),
    GrxCountry(
      id: GrxCountryId.SR,
      code: '+597',
      name: 'Suriname',
      flag: 'suriname_flag',
    ),
    GrxCountry(
      id: GrxCountryId.TJ,
      code: '+992',
      name: 'Tadjiquistão',
      flag: 'tajikistan_flag',
    ),
    GrxCountry(
      id: GrxCountryId.TH,
      code: '+66',
      name: 'Tailândia',
      flag: 'thailand_flag',
    ),
    GrxCountry(
      id: GrxCountryId.TW,
      code: '+886',
      name: 'Taiwan',
      flag: 'taiwan_flag',
    ),
    GrxCountry(
      id: GrxCountryId.TZ,
      code: '+255',
      name: 'Tanzânia',
      flag: 'tanzania_flag',
    ),
    GrxCountry(
      id: GrxCountryId.IO,
      code: '+246',
      name: 'Território Britânico do Oceano Índico',
      flag: 'british_indian_ocean_territory_flag',
    ),
    GrxCountry(
      id: GrxCountryId.TL,
      code: '+670',
      name: 'Timor Leste',
      flag: 'east_timor_flag',
    ),
    GrxCountry(
      id: GrxCountryId.TG,
      code: '+228',
      name: 'Togo',
      flag: 'togo_flag',
    ),
    GrxCountry(
      id: GrxCountryId.TK,
      code: '+690',
      name: 'Tokelau',
      flag: 'tokelau_flag',
    ),
    GrxCountry(
      id: GrxCountryId.TO,
      code: '+676',
      name: 'Tonga',
      flag: 'tonga_flag',
    ),
    GrxCountry(
      id: GrxCountryId.TT,
      code: '+1',
      name: 'Trinidad e Tobago',
      flag: 'trinidad_and_tobago_flag',
    ),
    GrxCountry(
      id: GrxCountryId.TN,
      code: '+216',
      name: 'Tunísia',
      flag: 'tunisia_flag',
    ),
    GrxCountry(
      id: GrxCountryId.TC,
      code: '+1',
      name: 'Turcas e Caicos',
      flag: 'turks_and_caicos_flag',
    ),
    GrxCountry(
      id: GrxCountryId.TM,
      code: '+993',
      name: 'Turquemenistão',
      flag: 'turkmenistan_flag',
    ),
    GrxCountry(
      id: GrxCountryId.TR,
      code: '+90',
      name: 'Turquia',
      flag: 'turkey_flag',
    ),
    GrxCountry(
      id: GrxCountryId.TV,
      code: '+638',
      name: 'Tuvalu',
      flag: 'tuvalu_flag',
    ),
    GrxCountry(
      id: GrxCountryId.UA,
      code: '+380',
      name: 'Ucrânia',
      flag: 'ukraine_flag',
    ),
    GrxCountry(
      id: GrxCountryId.UG,
      code: '+256',
      name: 'Uganda',
      flag: 'uganda_flag',
    ),
    GrxCountry(
      id: GrxCountryId.UZ,
      code: '+998',
      name: 'Uzbequistão',
      flag: 'uzbekistn_flag',
    ),
    GrxCountry(
      id: GrxCountryId.VU,
      code: '+678',
      name: 'Vanuatu',
      flag: 'vanuatu_flag',
    ),
    GrxCountry(
      id: GrxCountryId.VA,
      code: '+379',
      name: 'Vaticano',
      flag: 'vatican_city_flag',
    ),
    GrxCountry(
      id: GrxCountryId.VE,
      code: '+58',
      name: 'Venezuela',
      flag: 'venezuela_flag',
    ),
    GrxCountry(
      id: GrxCountryId.VN,
      code: '+84',
      name: 'Vietnã',
      flag: 'vietnam_flag',
    ),
    GrxCountry(
      id: GrxCountryId.ZM,
      code: '+260',
      name: 'Zâmbia',
      flag: 'zambia_flag',
    ),
    GrxCountry(
      id: GrxCountryId.ZW,
      code: '+263',
      name: 'Zimbábue',
      flag: 'zimbabwe_flag',
    ),
  ];
}
