name: Trigger on tag push

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Exemplo de Job
        run: echo "Tag push foi realizada!"
