# This is a basic workflow to help you get started with Actions

name: Publish Package

# Controls when the workflow will run
on:
  push:
    tags: ['v*']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests:
    name: Run Automated Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test

  publish:
    name: Upload package to pub.dev
    needs: tests
    uses: dart-lang/ecosystem/.github/workflows/publish.yaml@main
    permissions:
      id-token: write
      pull-requests: write
