name: Create tag

# Controls when the workflow will run
on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  auto-gen-tag:
    name: Auto Generate Tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.gen-tag-step.outputs.tagname }}
    steps:
      - uses: actions/checkout@v3
      - uses: jacopocarlini/action-autotag@3.0.0
        id: gen-tag-step
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          tag_prefix: 'v'
